### ISSUE TITLE
dmx_usb_module failed to build on kernel 6.6

### ISSUE THREAD

**Issue by CharlesMengCA** [lowlander/dmx_usb_module#11]
Hi,

When I tried to build dmx_usb_module for Linux Kernel 6.6.18, I got following error.

Could you help?

Thanks,

```
 CC [M]  /home/cm/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/dmx_usb_module-19.12.1/dmx_usb.o
/home/cm/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/dmx_usb_module-19.12.1/dmx_usb.c:100:47: error: macro "DEFINE_SEMAPHORE" requires 2 arguments, but only 1 given
  100 |         static DEFINE_SEMAPHORE(disconnect_sem);
      |                                               ^
In file included from ./include/linux/fs.h:25,
                 from ./arch/arm64/include/asm/elf.h:141,
                 from ./include/linux/elf.h:6,
                 from ./include/linux/module.h:19,
                 from /home/cm/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/dmx_usb_module-19.12.1/dmx_usb.c:20:
./include/linux/semaphore.h:34: note: macro "DEFINE_SEMAPHORE" defined here
   34 | #define DEFINE_SEMAPHORE(_name, _n)     \
      | 
/home/cm/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/dmx_usb_module-19.12.1/dmx_usb.c:100:16: error: type defaults to 'int' in declaration of 'DEFINE_SEMAPHORE' [-Werror=implicit-int]
  100 |         static DEFINE_SEMAPHORE(disconnect_sem);
      |                ^~~~~~~~~~~~~~~~
/home/cm/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/dmx_usb_module-19.12.1/dmx_usb.c: In function 'dmx_usb_open':
/home/cm/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/dmx_usb_module-19.12.1/dmx_usb.c:277:16: error: 'disconnect_sem' undeclared (first use in this function)
  277 |         down (&disconnect_sem);
      |                ^~~~~~~~~~~~~~
/home/cm/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/dmx_usb_module-19.12.1/dmx_usb.c:277:16: note: each undeclared identifier is reported only once for each function it appears in
/home/cm/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/dmx_usb_module-19.12.1/dmx_usb.c: In function 'dmx_usb_disconnect':
/home/cm/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/dmx_usb_module-19.12.1/dmx_usb.c:677:16: error: 'disconnect_sem' undeclared (first use in this function)
  677 |         down (&disconnect_sem);
      |                ^~~~~~~~~~~~~~
/home/cm/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/dmx_usb_module-19.12.1/dmx_usb.c: At top level:
/home/cm/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/dmx_usb_module-19.12.1/dmx_usb.c:100:16: error: 'DEFINE_SEMAPHORE' defined but not used [-Werror=unused-variable]
  100 |         static DEFINE_SEMAPHORE(disconnect_sem);
      |                ^~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[7]: *** [scripts/Makefile.build:243: /home/cm/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/dmx_usb_module-19.12.1/dmx_usb.o] Error 1
make[6]: *** [/home/cm/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/linux-6.6.18/Makefile:1913: /home/cm/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/dmx_usb_module-19.12.1] Error 2
make[5]: *** [Makefile:234: __sub-make] Error 2
make[5]: Leaving directory '/home/cm/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/linux-6.6.18'
make[4]: *** [Makefile:15: default] Error 2
make[4]: Leaving directory '/home/cm/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/dmx_usb_module-19.12.1'
make[3]: *** [Makefile:58: /home/cm/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/dmx_usb_module-19.12.1/.built] Error 2
make[3]: Leaving directory '/home/cm/openwrt/feeds/packages/libs/dmx_usb_module'
time: package/feeds/packages/dmx_usb_module/compile#0.74#0.14#0.86
    ERROR: package/feeds/packages/dmx_usb_module failed to build.

```

**Comment by nasbdh9** [comment]
```
make[3]: Entering directory '/home/nasbdh9/op2/feeds/packages/libs/dmx_usb_module'
mkdir -p /home/nasbdh9/op2/dl
SHELL= flock /home/nasbdh9/op2/tmp/.dmx_usb_module-19.12.1.tar.gz.flock -c '    /home/nasbdh9/op2/scripts/download.pl "/home/nasbdh9/op2/dl" "dmx_usb_module-19.12.1.tar.gz" "fabeb5500b55197338dda45d07374e5edc837bc18df3ac3114b442fe47cf1b68" "" "https://codeload.github.com/lowlander/dmx_usb_module/tar.gz/V19.12.1?"    '
+ curl -f --connect-timeout 20 --retry 5 --location https://codeload.github.com/lowlander/dmx_usb_module/tar.gz/V19.12.1?/dmx_usb_module-19.12.1.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 15423    0 15423    0     0  16304      0 --:--:-- --:--:-- --:--:-- 16303
touch /home/nasbdh9/op2/build_dir/target-i386_pentium-mmx_musl/linux-x86_geode/dmx_usb_module-19.12.1/.prepared_eb48427ac809017340682e09886f4f3a_6664517399ebbbc92a37c5bb081b5c53_check
. /home/nasbdh9/op2/include/shell.sh; /home/nasbdh9/op2/staging_dir/host/bin/libdeflate-gzip -dc /home/nasbdh9/op2/dl/dmx_usb_module-19.12.1.tar.gz | tar -C /home/nasbdh9/op2/build_dir/target-i386_pentium-mmx_musl/linux-x86_geode/dmx_usb_module-19.12.1/.. -xf -
[ ! -d ./src/ ] || cp -fpR ./src/. /home/nasbdh9/op2/build_dir/target-i386_pentium-mmx_musl/linux-x86_geode/dmx_usb_module-19.12.1

Applying /home/nasbdh9/op2/feeds/packages/libs/dmx_usb_module/patches/001-dmx_usb_Makefile.patch using plaintext:
patching file Makefile

Applying /home/nasbdh9/op2/feeds/packages/libs/dmx_usb_module/patches/100-fix-compilation-warning-wrong-cast.patch using plaintext:
patching file dmx_usb.c
touch /home/nasbdh9/op2/build_dir/target-i386_pentium-mmx_musl/linux-x86_geode/dmx_usb_module-19.12.1/.prepared_eb48427ac809017340682e09886f4f3a_6664517399ebbbc92a37c5bb081b5c53
rm -f /home/nasbdh9/op2/build_dir/target-i386_pentium-mmx_musl/linux-x86_geode/dmx_usb_module-19.12.1/.configured_*
rm -f /home/nasbdh9/op2/staging_dir/target-i386_pentium-mmx_musl/stamp/.dmx_usb_module_installed
(cd /home/nasbdh9/op2/build_dir/target-i386_pentium-mmx_musl/linux-x86_geode/dmx_usb_module-19.12.1/./; if [ -x ./configure ]; then find /home/nasbdh9/op2/build_dir/target-i386_pentium-mmx_musl/linux-x86_geode/dmx_usb_module-19.12.1/ -name config.guess | xargs -r chmod u+w; find /home/nasbdh9/op2/build_dir/target-i386_pentium-mmx_musl/linux-x86_geode/dmx_usb_module-19.12.1/ -name config.guess | xargs -r -n1 cp --remove-destination /home/nasbdh9/op2/scripts/config.guess; find /home/nasbdh9/op2/build_dir/target-i386_pentium-mmx_musl/linux-x86_geode/dmx_usb_module-19.12.1/ -name config.sub | xargs -r chmod u+w; find /home/nasbdh9/op2/build_dir/target-i386_pentium-mmx_musl/linux-x86_geode/dmx_usb_module-19.12.1/ -name config.sub | xargs -r -n1 cp --remove-destination /home/nasbdh9/op2/scripts/config.sub; AR="i486-openwrt-linux-musl-gcc-ar" AS="i486-openwrt-linux-musl-gcc -c -Os -pipe -march=pentium-mmx -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/home/nasbdh9/op2/build_dir/target-i386_pentium-mmx_musl/linux-x86_geode/dmx_usb_module-19.12.1=dmx_usb_module-19.12.1 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" LD="i486-openwrt-linux-musl-ld.bfd" NM="i486-openwrt-linux-musl-gcc-nm" CC="i486-openwrt-linux-musl-gcc" GCC="i486-openwrt-linux-musl-gcc" CXX="i486-openwrt-linux-musl-g++" RANLIB="i486-openwrt-linux-musl-gcc-ranlib" STRIP=i486-openwrt-linux-musl-strip OBJCOPY=i486-openwrt-linux-musl-objcopy OBJDUMP=i486-openwrt-linux-musl-objdump SIZE=i486-openwrt-linux-musl-size CFLAGS="-Os -pipe -march=pentium-mmx -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/home/nasbdh9/op2/build_dir/target-i386_pentium-mmx_musl/linux-x86_geode/dmx_usb_module-19.12.1=dmx_usb_module-19.12.1 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro " CXXFLAGS="-Os -pipe -march=pentium-mmx -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/home/nasbdh9/op2/build_dir/target-i386_pentium-mmx_musl/linux-x86_geode/dmx_usb_module-19.12.1=dmx_usb_module-19.12.1 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro " CPPFLAGS="-I/home/nasbdh9/op2/staging_dir/toolchain-i386_pentium-mmx_gcc-12.3.0_musl/usr/include -I/home/nasbdh9/op2/staging_dir/toolchain-i386_pentium-mmx_gcc-12.3.0_musl/include -I/home/nasbdh9/op2/staging_dir/toolchain-i386_pentium-mmx_gcc-12.3.0_musl/include/fortify " LDFLAGS="-L/home/nasbdh9/op2/staging_dir/toolchain-i386_pentium-mmx_gcc-12.3.0_musl/usr/lib -L/home/nasbdh9/op2/staging_dir/toolchain-i386_pentium-mmx_gcc-12.3.0_musl/lib -fuse-ld=bfd -znow -zrelro "   ./configure --target=i486-openwrt-linux --host=i486-openwrt-linux --build=x86_64-pc-linux-gnu --disable-dependency-tracking --program-prefix="" --program-suffix="" --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --libexecdir=/usr/lib --sysconfdir=/etc --datadir=/usr/share --localstatedir=/var --mandir=/usr/man --infodir=/usr/info --disable-nls  ; fi; )
touch /home/nasbdh9/op2/build_dir/target-i386_pentium-mmx_musl/linux-x86_geode/dmx_usb_module-19.12.1/.configured_68b329da9893e34099c7d8ad5cb9c940
rm -f /home/nasbdh9/op2/build_dir/target-i386_pentium-mmx_musl/linux-x86_geode/dmx_usb_module-19.12.1/.built
touch /home/nasbdh9/op2/build_dir/target-i386_pentium-mmx_musl/linux-x86_geode/dmx_usb_module-19.12.1/.built_check
make -C /home/nasbdh9/op2/build_dir/target-i386_pentium-mmx_musl/linux-x86_geode/dmx_usb_module-19.12.1 PATH="/home/nasbdh9/op2/staging_dir/toolchain-i386_pentium-mmx_gcc-12.3.0_musl/bin:/home/nasbdh9/op2/staging_dir/toolchain-i386_pentium-mmx_gcc-12.3.0_musl/bin:/home/nasbdh9/op2/staging_dir/host/bin:/home/nasbdh9/op2/staging_dir/toolchain-i386_pentium-mmx_gcc-12.3.0_musl/bin:/home/nasbdh9/op2/staging_dir/host/bin:/home/nasbdh9/op2/staging_dir/host/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin" ARCH="x86" CROSS_COMPILE="i486-openwrt-linux-musl-" TARGET="" TOOLPREFIX="i486-openwrt-linux-musl-" TOOLPATH="i486-openwrt-linux-musl-" KERNELPATH="/home/nasbdh9/op2/build_dir/target-i386_pentium-mmx_musl/linux-x86_geode/linux-6.6.18" LDOPTS=" " M=/home/nasbdh9/op2/build_dir/target-i386_pentium-mmx_musl/linux-x86_geode/dmx_usb_module-19.12.1
make[4]: Entering directory '/home/nasbdh9/op2/build_dir/target-i386_pentium-mmx_musl/linux-x86_geode/dmx_usb_module-19.12.1'
make -C /home/nasbdh9/op2/build_dir/target-i386_pentium-mmx_musl/linux-x86_geode/linux-6.6.18 M=/home/nasbdh9/op2/build_dir/target-i386_pentium-mmx_musl/linux-x86_geode/dmx_usb_module-19.12.1
make[5]: Entering directory '/home/nasbdh9/op2/build_dir/target-i386_pentium-mmx_musl/linux-x86_geode/linux-6.6.18'
  CC [M]  /home/nasbdh9/op2/build_dir/target-i386_pentium-mmx_musl/linux-x86_geode/dmx_usb_module-19.12.1/dmx_usb.o
/home/nasbdh9/op2/build_dir/target-i386_pentium-mmx_musl/linux-x86_geode/dmx_usb_module-19.12.1/dmx_usb.c:100:47: error: macro "DEFINE_SEMAPHORE" requires 2 arguments, but only 1 given
  100 |         static DEFINE_SEMAPHORE(disconnect_sem);
      |                                               ^
In file included from ./include/linux/fs.h:25,
                 from ./include/linux/usb.h:20,
                 from /home/nasbdh9/op2/build_dir/target-i386_pentium-mmx_musl/linux-x86_geode/dmx_usb_module-19.12.1/dmx_usb.c:23:
./include/linux/semaphore.h:34: note: macro "DEFINE_SEMAPHORE" defined here
   34 | #define DEFINE_SEMAPHORE(_name, _n)     \
      |
/home/nasbdh9/op2/build_dir/target-i386_pentium-mmx_musl/linux-x86_geode/dmx_usb_module-19.12.1/dmx_usb.c:100:16: error: type defaults to 'int' in declaration of 'DEFINE_SEMAPHORE' [-Werror=implicit-int]
  100 |         static DEFINE_SEMAPHORE(disconnect_sem);
      |                ^~~~~~~~~~~~~~~~
/home/nasbdh9/op2/build_dir/target-i386_pentium-mmx_musl/linux-x86_geode/dmx_usb_module-19.12.1/dmx_usb.c: In function 'dmx_usb_open':
/home/nasbdh9/op2/build_dir/target-i386_pentium-mmx_musl/linux-x86_geode/dmx_usb_module-19.12.1/dmx_usb.c:277:16: error: 'disconnect_sem' undeclared (first use in this function)
  277 |         down (&disconnect_sem);
      |                ^~~~~~~~~~~~~~
/home/nasbdh9/op2/build_dir/target-i386_pentium-mmx_musl/linux-x86_geode/dmx_usb_module-19.12.1/dmx_usb.c:277:16: note: each undeclared identifier is reported only once for each function it appears in
/home/nasbdh9/op2/build_dir/target-i386_pentium-mmx_musl/linux-x86_geode/dmx_usb_module-19.12.1/dmx_usb.c: In function 'dmx_usb_disconnect':
/home/nasbdh9/op2/build_dir/target-i386_pentium-mmx_musl/linux-x86_geode/dmx_usb_module-19.12.1/dmx_usb.c:677:16: error: 'disconnect_sem' undeclared (first use in this function)
  677 |         down (&disconnect_sem);
      |                ^~~~~~~~~~~~~~
/home/nasbdh9/op2/build_dir/target-i386_pentium-mmx_musl/linux-x86_geode/dmx_usb_module-19.12.1/dmx_usb.c: At top level:
/home/nasbdh9/op2/build_dir/target-i386_pentium-mmx_musl/linux-x86_geode/dmx_usb_module-19.12.1/dmx_usb.c:100:16: warning: 'DEFINE_SEMAPHORE' defined but not used [-Wunused-variable]
  100 |         static DEFINE_SEMAPHORE(disconnect_sem);
      |                ^~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[7]: *** [scripts/Makefile.build:243: /home/nasbdh9/op2/build_dir/target-i386_pentium-mmx_musl/linux-x86_geode/dmx_usb_module-19.12.1/dmx_usb.o] Error 1
make[6]: *** [/home/nasbdh9/op2/build_dir/target-i386_pentium-mmx_musl/linux-x86_geode/linux-6.6.18/Makefile:1913: /home/nasbdh9/op2/build_dir/target-i386_pentium-mmx_musl/linux-x86_geode/dmx_usb_module-19.12.1] Error 2
make[5]: *** [Makefile:234: __sub-make] Error 2
make[5]: Leaving directory '/home/nasbdh9/op2/build_dir/target-i386_pentium-mmx_musl/linux-x86_geode/linux-6.6.18'
make[4]: *** [Makefile:15: default] Error 2
make[4]: Leaving directory '/home/nasbdh9/op2/build_dir/target-i386_pentium-mmx_musl/linux-x86_geode/dmx_usb_module-19.12.1'
make[3]: *** [Makefile:58: /home/nasbdh9/op2/build_dir/target-i386_pentium-mmx_musl/linux-x86_geode/dmx_usb_module-19.12.1/.built] Error 2
make[3]: Leaving directory '/home/nasbdh9/op2/feeds/packages/libs/dmx_usb_module'
time: package/feeds/packages/dmx_usb_module/compile#0.69#0.16#1.73
    ERROR: package/feeds/packages/dmx_usb_module failed to build.
make[2]: *** [package/Makefile:128: package/feeds/packages/dmx_usb_module/compile] Error 1
```

Same here

**Comment by lowlander** [comment]
Sorry for the slow reply (again), but it should be fixed in master now.
